Token Revoke
CyFy-Blockchain/auth pull request #17
Opened 2024-11-27 02:43 UTC by MHassanTariq

# 📝 Description

This PR revokes all accesses with expired tokens. 
1. Access Tokens and Refresh Tokens are expired based on the passed env variables
2. CronJob runs to clean up db for removing all expired tokens

For more information on tokens are managed, please consult [this doc](https://docs.google.com/document/d/1N2D2KbLhIqoOMRtxZllHgyv76XPSpDK6uJrOgOK178c/edit?tab=t.0). 

# ♻️ Change Log

- Expiration for Tokens (auth Mapping, and users)
- Adding Timestamps in with tables (all entities to include this change)
- CronJobs to delete all expired token data

# 🏛️ Architecture

NA

# 🧪 Tests

NA

2024-11-28 16:49 UTC, MHA10 requested changes

2024-11-28 16:49 UTC, MHA10 commented on src/modules/crons/cleanup.service.ts
> +    console.log('Running token cleanup cron...');
console.info*

2024-11-28 16:49 UTC, MHA10 commented on src/modules/crons/cleanup.service.ts
> +    console.log(
console.info

2024-11-28 16:49 UTC, MHA10 commented on src/modules/crons/crons.module.ts
> +import { DbCleanupService } from './cleanup.service';
absolute paths

2024-11-28 16:49 UTC, MHA10 commented on src/modules/orgs/dto/orgs.mapper.ts
> +export function mapOrgToOrgDto(org: Organization): OrgDto {
do we need this? as the fields are exactly the same.

2024-11-28 16:49 UTC, MHA10 commented on src/modules/users/controllers/users.controller.ts
> +  @Get('/refreshToken')
path to be refresh-token

2024-11-28 16:52 UTC, MHassanTariq commented on src/modules/crons/crons.module.ts
> +import { DbCleanupService } from './cleanup.service';
Resolving this since I'll be creating a different PR for paths specifically.

2024-11-29 00:13 UTC, MHassanTariq commented on src/modules/orgs/dto/orgs.mapper.ts
> +export function mapOrgToOrgDto(org: Organization): OrgDto {
The entity Organization contains an additional attribute, `members`. When querying DB for Organization, list of members is also returned. This mapper is intended to remove the noise from the response.

2024-11-29 00:14 UTC, MHassanTariq commented on src/modules/users/controllers/users.controller.ts
> +  @Get('/refreshToken')
Good catch. Updated!

2024-11-29 18:14 UTC, MHA10 commented on src/modules/orgs/dto/orgs.mapper.ts
> +export function mapOrgToOrgDto(org: Organization): OrgDto {
Okay, sounds good then.

2024-11-29 18:15 UTC, MHA10 approved these changes

2024-11-29 22:39 UTC, merged